apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: db
  selector:
    app: postgres
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:11.3-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: POSTGRES_DB
          value: WORKSHOP
        - name: PGDATA
          value: /data
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: data-pvc-storage
          mountPath: /data
      volumes:
      - persistentVolumeClaim:
          claimName: data-pvc-claim
        name: data-pvc-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: QXczczBtMw==
