apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: db
  selector:
    app: postgres
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:11.3-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
              #- name: POSTGRES_DB
              #value: WORKSHOP
        - name: PGDATA
          value: /data
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: data-pvc-storage
          mountPath: /data
        - name: init-db-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: data-pvc-storage
        persistentVolumeClaim:
          claimName: data-pvc-claim
      - name: init-db-sql
        configMap:
          name: init-db-sql
---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: QXczczBtMw==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-sql
data:
  init-db.sql: |
    CREATE database WORKSHOP;
    grant all privileges on database WORKSHOP to postgres;
    CREATE TABLE account(
      user_id serial PRIMARY KEY,
      username VARCHAR (50) UNIQUE NOT NULL,
      password VARCHAR (50) NOT NULL,
      email VARCHAR (355) UNIQUE NOT NULL,
      created_on TIMESTAMP NOT NULL,
      last_login TIMESTAMP
    );
